server:
  port: 8080

spring:
  jpa:
    show-sql: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:boleta;MODE=MYSQL
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      idle-timeout: 10000
      connection-timeout: 30000
      auto-commit: false
      pool-name: engine_pool_ms
      minimum-idle: 5

  flyway:
    baselineOnMigrate: true
    enabled: true
    table: schema_version_intercorp

  jackson:
    default-property-inclusion: non_null

logging:
  config: classpath:logging/logback.xml